# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"
baseURL = "https://hotloncon1.github.io/aws-lab000055/"
canonifyURLs = true
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "journeyoftheaverageguy@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "Creating an Authenticated Single Page Application (SPA)"
weight = 1
languageName = "English"


[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/660548818043427/"
weight = 20

[Languages.vi]
title = "Tạo một Single Page Application(SPA) được xác thực"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/660548818043427/"
weight = 20

